In [1]:
import random

In [2]:
numbers = []
for i in range(15):
    numbers.append(random.randint(0,100))

In [3]:
numbers

[68, 94, 53, 23, 49, 4, 64, 61, 68, 77, 93, 42, 50, 40, 31]

In [4]:
names = ['James', 'Sally', 'George', 'Kristen', 'Alex', 'Melissa']

- J[0],A[1],M[2],E[3],S[4]
- The numbers are called the index

In [5]:
names[0]

'James'

In [6]:
numbers

[68, 94, 53, 23, 49, 4, 64, 61, 68, 77, 93, 42, 50, 40, 31]

In [7]:
numbers[-1] #use this to find last number in a list

31

In [8]:
len(names)

6

To find length of list or string use len(...)

In [9]:
numbers[5] = 134

In [10]:
names[0] = 'John'

In [11]:
names

['John', 'Sally', 'George', 'Kristen', 'Alex', 'Melissa']

In [12]:
age = 10

In [13]:
age+=1

In [14]:
age

11

In [15]:
numbers.append(110)

In [16]:
numbers + names;

In [17]:
numbers

[68, 94, 53, 23, 49, 134, 64, 61, 68, 77, 93, 42, 50, 40, 31, 110]

In [18]:
numbers[4:8]

[49, 134, 64, 61]

In [19]:
numbers[7:]

[61, 68, 77, 93, 42, 50, 40, 31, 110]

Use 4:8 to find range from 4-7 in list |||
Use 7: to find 7 to end and :7 to find 7 to beginning

In [20]:
numbers[4:15:2]

[49, 64, 68, 93, 50, 31]

This gives every other element since using 2

In [21]:
numbers[-4:]

[50, 40, 31, 110]

This gives last 4 numbers

In [22]:
names

['John', 'Sally', 'George', 'Kristen', 'Alex', 'Melissa']

In [23]:
names[2:4]

['George', 'Kristen']

In [24]:
names

['John', 'Sally', 'George', 'Kristen', 'Alex', 'Melissa']

In [25]:
names[2:] = ["Chris", "Paul", "Ben"]

In [26]:
names

['John', 'Sally', 'Chris', 'Paul', 'Ben']

In [27]:
names[-1] = "Greg"

In [28]:
names

['John', 'Sally', 'Chris', 'Paul', 'Greg']

In [29]:
len(names)

5

In [30]:
del names[-1]

In [31]:
names

['John', 'Sally', 'Chris', 'Paul']

In [32]:
sorted(numbers)

[23, 31, 40, 42, 49, 50, 53, 61, 64, 68, 68, 77, 93, 94, 110, 134]

In [33]:
sorted_numbers = sorted(numbers)

In [34]:
numbers.sort()

In [35]:
numbers

[23, 31, 40, 42, 49, 50, 53, 61, 64, 68, 68, 77, 93, 94, 110, 134]

In [36]:
numbers.sort(reverse = True)

In [37]:
numbers

[134, 110, 94, 93, 77, 68, 68, 64, 61, 53, 50, 49, 42, 40, 31, 23]

In [38]:
numbers.sort()

In [39]:
numbers = [7, 13, 22, 53, 54, 63, 64, 71, 73, 84]

In [40]:
numbers

[7, 13, 22, 53, 54, 63, 64, 71, 73, 84]

In [41]:
numbers.index(71)

7

In [42]:
64 in numbers

True

In [43]:
squares = [number**2 for number in numbers]

In [44]:
squares

[49, 169, 484, 2809, 2916, 3969, 4096, 5041, 5329, 7056]

In [45]:
[len(name) for name in names]

[4, 5, 5, 4]

In [46]:
[print(name) for name in names]

John
Sally
Chris
Paul


[None, None, None, None]

In [47]:
numbers = []
for i in range(20):
    numbers.append(random.randint(0,10))

In [48]:
numbers = []
for i in range(20):
    numbers.append(random.randint(0,10))

In [49]:
numbers2 =[random.randrange(1,10,1) for i  in range(10)]

In [50]:
numbers2

[6, 4, 6, 9, 9, 5, 8, 9, 1, 4]

In [51]:
all(number>0 for number in numbers2)

True

In [52]:
dir(numbers)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [53]:
a = 10
b = a

In [54]:
print(a,b)

10 10


In [55]:
n2 = numbers

In [56]:
print(numbers,n2)

[1, 7, 2, 6, 4, 8, 9, 8, 0, 9, 0, 7, 9, 8, 7, 7, 9, 10, 7, 6] [1, 7, 2, 6, 4, 8, 9, 8, 0, 9, 0, 7, 9, 8, 7, 7, 9, 10, 7, 6]


In [57]:
list1 = [1,2,3,4,5,6,7,8,9]

In [58]:
#dir(list)

In [59]:
# functions in a class are called methods

In [60]:
#Methods consist of functions

In [61]:
#Classes have behaviors and attributes. Behaviors are methods

In [62]:
list2 = list1

In [63]:
list2[5]=10

In [64]:
list2

[1, 2, 3, 4, 5, 10, 7, 8, 9]

In [65]:
list1

[1, 2, 3, 4, 5, 10, 7, 8, 9]

In [66]:
list3 = list1.copy()

In [67]:
list3[0]=10

In [68]:
list1

[1, 2, 3, 4, 5, 10, 7, 8, 9]

In [69]:
list3

[10, 2, 3, 4, 5, 10, 7, 8, 9]

In [70]:
#dir(list1)

In [71]:
numbers.sort?

Signature: numbers.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method

In [72]:
# _.sort changes list forever

In [73]:
numbers.reverse?

Signature: numbers.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method

In [74]:
# .append adds to end of list

In [75]:
numbers.extend?

Signature: numbers.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method

In [76]:
numbers.pop?

Signature: numbers.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method

In [77]:
# .pop removes from end of list

In [78]:
# module is a file that contains functions

In [79]:
# you can use dir(module) to find what you can do with modules

In [80]:
t1 = ("George", "Costanza", 88, 92, 2004)

In [81]:
t1[4]

2004

In [82]:
t1

('George', 'Costanza', 88, 92, 2004)

In [83]:
t2 = (32, 34, 36, 38, 40, 42, 44)

In [84]:
t3 = (32, 34, 36, 38, 40, 42,[2,5,6])

In [85]:
t3[6][1]=12

In [86]:
t3

(32, 34, 36, 38, 40, 42, [2, 12, 6])

In [87]:
t3[6].sort()

In [88]:
t3

(32, 34, 36, 38, 40, 42, [2, 6, 12])

In [89]:
list4 = [t1,t3]

In [90]:
list4

[('George', 'Costanza', 88, 92, 2004), (32, 34, 36, 38, 40, 42, [2, 6, 12])]

In [91]:
list4[1][6][0]

2

### Zip function allows us to combine lists (Will Help On #4)

In [92]:
teams = ['Bellarmine', 'Liberty', 'EKU', 'North Florida', 'Lipscomb']
wins = [6,8,3,6,7]
losses = [7,3,5,6,7]

In [93]:
agg = []
for team, win, loss in zip(teams, wins, losses):
    agg.append((team, win, loss))

In [94]:
agg

[('Bellarmine', 6, 7),
 ('Liberty', 8, 3),
 ('EKU', 3, 5),
 ('North Florida', 6, 6),
 ('Lipscomb', 7, 7)]

In [95]:
#List Comp
#[x**3 for x in range(1,100)]

### Genterator Expression

In [96]:
def is_mod4(n):
    return n%4==0

In [97]:
for value in (x**3 for x in range(1,100,2)):
    print(f"Is {value} a multiple of 4? {is_mod4(value)}")

Is 1 a multiple of 4? False
Is 27 a multiple of 4? False
Is 125 a multiple of 4? False
Is 343 a multiple of 4? False
Is 729 a multiple of 4? False
Is 1331 a multiple of 4? False
Is 2197 a multiple of 4? False
Is 3375 a multiple of 4? False
Is 4913 a multiple of 4? False
Is 6859 a multiple of 4? False
Is 9261 a multiple of 4? False
Is 12167 a multiple of 4? False
Is 15625 a multiple of 4? False
Is 19683 a multiple of 4? False
Is 24389 a multiple of 4? False
Is 29791 a multiple of 4? False
Is 35937 a multiple of 4? False
Is 42875 a multiple of 4? False
Is 50653 a multiple of 4? False
Is 59319 a multiple of 4? False
Is 68921 a multiple of 4? False
Is 79507 a multiple of 4? False
Is 91125 a multiple of 4? False
Is 103823 a multiple of 4? False
Is 117649 a multiple of 4? False
Is 132651 a multiple of 4? False
Is 148877 a multiple of 4? False
Is 166375 a multiple of 4? False
Is 185193 a multiple of 4? False
Is 205379 a multiple of 4? False
Is 226981 a multiple of 4? False
Is 250047 a multipl

In [98]:
import random

In [99]:
numbers = []
for i in range(100):
    numbers.append(random.randint(0,100))

In [100]:
print(numbers, end=' ')

[72, 23, 95, 7, 84, 91, 83, 97, 44, 73, 27, 89, 5, 60, 45, 81, 74, 18, 78, 97, 88, 61, 2, 29, 51, 8, 40, 20, 27, 22, 72, 70, 100, 94, 54, 75, 10, 13, 6, 62, 27, 54, 22, 44, 13, 67, 22, 46, 29, 45, 2, 97, 38, 32, 78, 68, 94, 24, 7, 3, 1, 95, 81, 80, 98, 90, 54, 91, 77, 11, 12, 47, 6, 63, 37, 79, 51, 16, 66, 73, 96, 73, 50, 2, 6, 48, 99, 36, 83, 0, 9, 22, 81, 74, 24, 40, 47, 62, 76, 86] 

In [101]:
import math
def is_perfect_square(n):
    if n<0:
        return False
    root = math.sqrt(n)
    return root.is_integer()

Filters work with funnction that return true/false

In [102]:
list(filter(is_perfect_square,numbers))  # creates list for verified numbers

[81, 100, 1, 81, 16, 36, 0, 9, 81]

In [103]:
list(filter(is_mod4,numbers))  # creates list for verified numbers

[72,
 84,
 44,
 60,
 88,
 8,
 40,
 20,
 72,
 100,
 44,
 32,
 68,
 24,
 80,
 12,
 16,
 96,
 48,
 36,
 0,
 24,
 40,
 76]

In [104]:
list(filter(lambda x: x%2==0, numbers)) ;

In [105]:
list(filter(lambda x: math.sqrt(x)<5, numbers))

[23,
 7,
 5,
 18,
 2,
 8,
 20,
 22,
 10,
 13,
 6,
 22,
 13,
 22,
 2,
 24,
 7,
 3,
 1,
 11,
 12,
 6,
 16,
 2,
 6,
 0,
 9,
 22,
 24]

In [106]:
states = ['Indiana', 'Illinios', 'Ohio', 'Tennesseee', 'West Virginia', 'Virginia', 'Missouri']
states.sort()

In [107]:
name_length = list(map(lambda x: len(x), states))

In [108]:
name_length

[8, 7, 8, 4, 10, 8, 13]

In [109]:
border_states = []
for state, length in zip(states, name_length):
    border_states.append((state, length))

In [110]:
border_states

[('Illinios', 8),
 ('Indiana', 7),
 ('Missouri', 8),
 ('Ohio', 4),
 ('Tennesseee', 10),
 ('Virginia', 8),
 ('West Virginia', 13)]

### Dictionary

In [111]:
d = {"KY": "Kentucky",
     "IN": "Indiana", 
     "IL": "Illinois",
     "OH": "Ohio",
     "TN": "Tennessee",
     "WV": "West Virginia",
     "VA": "Virginia",
     "MO": "Missouri"
    }
# THESE ARE KEY VALUE PAIRS

In [112]:
d["KY"]

'Kentucky'

### Sets

In [113]:
KY = {'IN','IL','WV','VA','OH','TN','MO'}

In [114]:
TN = {'KY','VA','NC','GA','AL','MS','AR','MO'}

In [115]:
for state in KY:
    print(f'{state}',end=' ')

TN WV IL OH IN MO VA 

In [116]:
KY | TN

{'AL', 'AR', 'GA', 'IL', 'IN', 'KY', 'MO', 'MS', 'NC', 'OH', 'TN', 'VA', 'WV'}

In [117]:
KY.union(TN)

{'AL', 'AR', 'GA', 'IL', 'IN', 'KY', 'MO', 'MS', 'NC', 'OH', 'TN', 'VA', 'WV'}

In [118]:
KY ^ TN

{'AL', 'AR', 'GA', 'IL', 'IN', 'KY', 'MS', 'NC', 'OH', 'TN', 'WV'}

### Numpy

In [1]:
import numpy as np
from PIL import Image

In [123]:
nums = np.array([10,10,45,32,54,67])   # how to create an array

In [125]:
nums.dtype      # how to test data type (.dtype)

dtype('int32')

In [126]:
nums2 = np.random.randint(0,100, size=(1,10))

In [127]:
nums2

array([[15, 28, 60, 57, 46, 49, 33, 18, 80, 13]])

In [138]:
num2d = np.array([[10,10,45],
                 [5,7,3],
                  [65,76,96]
                 ])

In [139]:
num2d

array([[10, 10, 45],
       [ 5,  7,  3],
       [65, 76, 96]])

In [134]:
num2d.shape    # .shape says 3x3 or 2x3 etc.

(3, 3)

In [142]:
num2d2 = np.random.randint(0,100, size=(3,5))

In [143]:
num2d2

array([[63, 85, 33, 69,  8],
       [31, 23, 32, 69, 84],
       [ 1, 30, 43, 55, 68]])

In [146]:
num2d2.size    # tells number of elements

15

In [147]:
num2d2.itemsize      # shows how many bytes

4

In [149]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [150]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [152]:
np.arange(5)     # creates an array from 0 to n-1

array([0, 1, 2, 3, 4])

In [176]:
num3 = np.arange(0,100,2)

In [177]:
num3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [178]:
np.linspace(0.0, 30, num=15)     # 0 is lower end point 1 is upper endpoint num=5 is total numbers evenly spaced

array([ 0.        ,  2.14285714,  4.28571429,  6.42857143,  8.57142857,
       10.71428571, 12.85714286, 15.        , 17.14285714, 19.28571429,
       21.42857143, 23.57142857, 25.71428571, 27.85714286, 30.        ])

In [181]:
num3 = num3.reshape(5,10)

In [182]:
num3.shape

(5, 10)

In [184]:
num3 * 5       # 5 is a scaler in this scenario

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490]])

In [185]:
num3.sum()

2450

In [187]:
num3

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [186]:
print(num3.sum(), num3.mean(), num3.std(), num3.var())

2450 49.0 28.861739379323623 833.0
